### ISSUE TITLE
很棒的项目，提交两个小反馈

### ISSUE THREAD

**Issue by eryajf** [CH563/shot-easy-website#1]
如题，非常优秀的项目，预祝项目有更好的未来发展。

这边体验时，遇到两个小问题。

1. padding调为了0，但是仍有漏出
 
<img width="634" alt="image" src="https://github.com/CH563/shot-easy-website/assets/33259379/f4d923c1-da28-4382-8e0a-7ca65f8872eb">

2. 当我设置为放大时，Canvas 的选项中auto隐藏到了页面之外

<img width="344" alt="image" src="https://github.com/CH563/shot-easy-website/assets/33259379/b31bd008-2dd6-432c-b6d5-55dc093bfb33">

**Comment by CH563** [comment]
欢迎使用新的版本，使用LeaferJS开发，支持使用功能和操作：

[https://screenshot.shoteasy.fun/](https://screenshot.shoteasy.fun/)
