### ISSUE TITLE
bug: 图片压缩后严重失真，且色彩丢失

### ISSUE THREAD

**Issue by tisfeng** [CH563/shot-easy-website#2]
<table>
    <tr>
        <td align="center">压缩前图片</td>
        <td align="center"">压缩后图片</td>
    </tr>
    <tr>
        <td><img src="https://github.com/CH563/shot-easy-website/assets/25194972/90e984cd-87d4-4027-9a6b-e4929cd1be34"></td>
        <td><img src="https://github.com/CH563/shot-easy-website/assets/25194972/f3887742-90b0-403a-be71-2f84e0b33f5f"></td>
    </tr>
</table>

**Comment by CH563** [comment]
感谢反馈，我优化一个版本和增加压缩质量的自由设置

**Comment by CH563** [comment]
![image](https://github.com/CH563/shot-easy-website/assets/17285134/e1b0fbad-ddd7-495d-af54-a6a6fc45bbf3)

使用ShotEasy压缩设置，调整压缩质量。有渐变色，基本调到90左右就跟原图没差了。

点击缩略图可以展开，查看对比。

**Comment by tisfeng** [comment]
ok，看起来改进了很多。
