### ISSUE TITLE
很优秀的项目，反馈2个小问题

### ISSUE THREAD

**Issue by o1laabs** [CH563/shot-easy-website#21]
1.美化功能：手机截图上传后，默认边距及调整边距，截图内容都显示不完整。
2.抠图功能：上传待扣背景的图片后，一直处理中，无法抠图。

**Comment by CH563** [comment]
> 1.美化功能：手机截图上传后，默认边距及调整边距，截图内容都显示不完整。 2.抠图功能：上传待扣背景的图片后，一直处理中，无法抠图。

感谢反馈，美化功能我优化一下这个细节。
抠图功能是使用了remove.bg 的API，有50次限制，重新添加新的KEY了

**Comment by o1laabs** [comment]
为大佬的效率点赞！太优秀啦！

________________________________
发件人: Chenliwen ***@***.***>
发送时间: 星期六, 七月 6, 2024 11:02:56 下午
收件人: CH563/shot-easy-website ***@***.***>
抄送: o1labs ***@***.***>; Author ***@***.***>
主题: Re: [CH563/shot-easy-website] 很优秀的项目，反馈2个小问题 (Issue #21)


1.美化功能：手机截图上传后，默认边距及调整边距，截图内容都显示不完整。 2.抠图功能：上传待扣背景的图片后，一直处理中，无法抠图。

感谢反馈，美化功能我优化一下这个细节。
抠图功能是使用了remove.bg 的API，有50次限制，重新添加新的KEY了

―

**Comment by CH563** [comment]
#23 已对手机模式下的边距兼容
