### ISSUE TITLE
很棒的项目

### ISSUE THREAD

**Issue by HaiwangTT** [CH563/shot-easy-website#24]
提个小建议：

比如在做教程的时候，给个图片放大镜，比如图某个部分引出放大，加个箭头引导，

**Comment by CH563** [comment]
感谢反馈，这个功能不错，立即加上

**Comment by CH563** [comment]
增加了一个局部放大效果，使用新的美化器：https://screenshot.shoteasy.fun/

如图示：

![image](https://github.com/user-attachments/assets/50921965-00ba-44c8-abda-492d0bcbb4c3)

**Comment by HaiwangTT** [comment]
![微信图片_20240826212144](https://github.com/user-attachments/assets/9b5e6591-6dbe-40c3-9bf3-657db1b770e6)
看看这种，要引出在局部放大，原地放大差点意思

**Comment by HaiwangTT** [comment]
https://github.com/user-attachments/assets/badef56b-bf47-43be-8848-3fae6c9fa237

还有这种也不错
